Fix `misc-use-internal-linkage`
Add missing `base/str.h` include to `tolower.cpp` for `str_utf8_tolower_codepoint` declaration. Declare functions and global variables as `static`. This revealed that some functions were conditionally unused.

```
src/base/dbg.cpp:13:18: warning: variable 'dbg_assert_failing' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   13 | std::atomic_bool dbg_assert_failing = false;
      |                  ^
      | static
src/base/dbg.cpp:14:20: warning: variable 'dbg_assert_handler' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   14 | DBG_ASSERT_HANDLER dbg_assert_handler;
      |                    ^
      | static
src/base/log.cpp:27:24: warning: variable 'global_logger' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   27 | std::atomic<ILogger *> global_logger = nullptr;
      |                        ^
      | static
src/base/log.cpp:28:23: error: variable 'scope_logger' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   28 | thread_local ILogger *scope_logger = nullptr;
      |                       ^
      | static
src/base/log.cpp:29:19: error: variable 'in_logger' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   29 | thread_local bool in_logger = false;
      |                   ^
      | static
src/base/net.cpp:62:6: warning: function 'net_buffer_init' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   62 | void net_buffer_init(NETSOCKET_BUFFER *buffer)
      |      ^
      | static
src/base/net.cpp:82:6: warning: function 'net_buffer_reinit' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   82 | void net_buffer_reinit(NETSOCKET_BUFFER *buffer)
      |      ^
      | static
src/base/net.cpp:92:6: warning: function 'net_buffer_simple' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   92 | void net_buffer_simple(NETSOCKET_BUFFER *buffer, char **buf, int *size)
      |      ^
      | static
src/base/net.cpp:208:6: warning: function 'net_addr_str_v6' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
  208 | void net_addr_str_v6(const unsigned short ip[8], int port, char *buffer, int buffer_size)
      |      ^
      | static
src/base/time.cpp:66:18: error: variable 'time_info_buf' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
   66 |         thread_local tm time_info_buf;
      |                         ^
      |         static
src/base/unicode/tolower.cpp:3:5: warning: function 'str_utf8_tolower_codepoint' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage]
    3 | int str_utf8_tolower_codepoint(int code)
      |     ^
      | static
```