Fix Emscripten CMake configuration due to `--preload-file`
Specify `--preload-file data` linker flag to preload data directory into the filesystem in the `CMakeLists.txt` file as an additional target link option instead of specifying it in the `Emscripten.toolchain` file, as the latter caused the CMake configuration steps to fail due to the `data` folder being missing during this phase:

```
error: data does not exist
em++: error: '/emsdk/upstream/emscripten/tools/file_packager cmTC_83f35.data --from-emcc --preload data' failed (returned 1)
```

This was causing the CMake configuration phase to take longer, but building seemed to work anyway because it eventually falls back to some working defaults.