Fix linking Rust tests with MinGW
Add missing library `uuid.lib` to fix linking error `undefined reference to FOLDERID_RoamingAppData`.

Consistently use suffix `.lib` for all libraries on Windows. The name `uuid` would have otherwise conflicted with the build target for the tool with the same name.

Closes #10508.