Update mariadb package name
Both ubuntu and debian throw the following error

```
$ sudo apt install libmariadbclient-dev
[sudo] password for chiller:
Package libmariadbclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libmariadb-dev-compat  libmariadb-dev

Error: Package 'libmariadbclient-dev' has no installation candidate
```