Fix gcc format-security warnings on build
BTW no-nullability-completeness flag seems is not recognized anymore and
can be dropped after this patch applied

FAILED: CMakeFiles/game-client.dir/src/game/client/components/hud.cpp.o
/usr/bin/g++ -DCONF_BACKEND_VULKAN -DCONF_INFORM_UPDATE -DCONF_OPENSSL -DCONF_WAVPACK_CLOSE_FILE -DCONF_WAVPACK_OPEN_FILE_INPUT_EX -DGAME_RELEASE_VERSION=\"18.3\" -DGLEW_STATIC -D_FORTIFY_SOURCE=2 -I/builddir/build/BUILD/ddnet-18.3/redhat-linux-build/src -I/builddir/build/BUILD/ddnet-18.3/src -I/builddir/build/BUILD/ddnet-18.3/src/rust-bridge -isystem /usr/include/freetype2 -isystem /usr/include/opus -isystem /usr/include/SDL2 -isystem /usr/include/wavpack -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libpng16 -isystem /usr/include/webp -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/sysprof-6 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -g -DNDEBUG -std=c++17 -fdiagnostics-color=always -fstack-protector-strong -fno-exceptions -Wall -Wextra -Wno-psabi -Wno-unused-parameter -Wno-missing-field-initializers -Wno-nullability-completeness -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wshadow=global -Wsuggest-override -Wclass-memaccess -MD -MT CMakeFiles/game-client.dir/src/game/client/components/hud.cpp.o -MF CMakeFiles/game-client.dir/src/game/client/components/hud.cpp.o.d -o CMakeFiles/game-client.dir/src/game/client/components/hud.cpp.o -c /builddir/build/BUILD/ddnet-18.3/src/game/client/components/hud.cpp
In file included from /builddir/build/BUILD/ddnet-18.3/src/engine/graphics.h:10,
                 from /builddir/build/BUILD/ddnet-18.3/src/game/client/components/hud.cpp:3:
/builddir/build/BUILD/ddnet-18.3/src/base/system.h: In instantiation of ‘int str_format_opt(char*, int, const char*, Args ...) [with Args = {}]’:
/builddir/build/BUILD/ddnet-18.3/src/game/client/components/hud.cpp:1623:13:   required from here
 1623 |                 str_format(aBuf, sizeof(aBuf), Localize("Server best:"));
/builddir/build/BUILD/ddnet-18.3/src/base/system.h:1238:26: error: format not a string literal and no format arguments [-Werror=format-security]
 1238 |         return str_format(buffer, buffer_size, format, args...);
      |                ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-nullability-completeness’ may have been intended to silence earlier diagnostics
cc1plus: some warnings being treated as errors