Fix twmap installation in CI
error: failed to compile `twmap-tools v0.3.1 (/home/runner/work/ddnet/ddnet/twmap/twmap-tools)`, intermediate artifacts can be found at `/home/runner/work/ddnet/ddnet/twmap/target`

Caused by:
  package `half v2.3.1` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0
  Either upgrade to rustc 1.70 or newer, or use
  cargo update -p half@2.3.1 --precise ver
  where `ver` is the latest version of `half` supporting rustc 1.69.0